const ACTIONS = {
    SIGNIN : "SIGNIN",
    UPDATE_MESSAGE : 'UPDATE_MESSAGE',
    REGISTER : "REGISTER",
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    LOGOUT : 'LOGOUT',
    ADD_CART : 'ADD_CART',
    REMOVE_CART: 'REMOVE_CART',
    PERSIST_USER : 'PERSIST_USER',
    ADD_QUANTITY : 'ADD_QUANTITY',
    MINUS_QUANTITY : 'MINUS_QUANTITY',
    ORDER_SUCCESS : 'ORDER_SUCCESS'
}


export default ACTIONS